# Generated by Django 4.2 on 2023-11-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even', '0003_alter_event_publish_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
